# Generated by Django 4.2.30 on 2026-07-11 05:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useridentity',
            name='school_email',
            field=models.EmailField(default='default@cc.ncu.edu.tw', max_length=254, unique=True, verbose_name='學校信箱'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='campus_id',
            field=models.CharField(max_length=9, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^\\d{9}$', message='學號必須為 9 位數字')], verbose_name='校園ID'),
        ),
    ]
