# Generated by Django 4.2.30 on 2026-07-18 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_review_is_deleted_review_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='contact_info',
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='event',
            name='organizer_nickname',
            field=models.CharField(default='', max_length=200),
        ),
    ]
