# Generated by Django 4.2.30 on 2026-07-28 14:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_event_contact_info_event_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='廣告標題')),
                ('image', models.ImageField(upload_to='ads/', verbose_name='廣告圖片')),
                ('url', models.URLField(blank=True, max_length=500, null=True, verbose_name='廣告連結')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否上架')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='campus_id',
            field=models.CharField(max_length=9, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9]{9}$', message='學號必須為 9 位英數字')], verbose_name='帳號ID'),
        ),
        migrations.CreateModel(
            name='OutsiderIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_name', models.CharField(max_length=50, verbose_name='使用者姓名')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='聯絡信箱')),
                ('occupation', models.CharField(max_length=100, verbose_name='職業')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='outsider_identity', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
