# Generated by Django 4.2.30 on 2026-08-04 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_emailverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='source',
            field=models.CharField(choices=[('web', 'Web'), ('line', 'LINE')], default='web', max_length=10, verbose_name='來源'),
        ),
        migrations.AddField(
            model_name='user',
            name='line_display_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='LINE 顯示名稱'),
        ),
        migrations.AddField(
            model_name='user',
            name='line_user_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='LINE User ID'),
        ),
    ]
