# Generated by Django 4.2.30 on 2026-08-16 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_event_attendees_event_join_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriftBottle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=200, verbose_name='推薦電影')),
                ('message', models.TextField(blank=True, null=True, verbose_name='推薦留言')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drift_bottles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
