# Generated by Django 4.2.30 on 2026-08-17 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_driftbottle'),
    ]

    operations = [
        migrations.AddField(
            model_name='driftbottle',
            name='fished_count',
            field=models.IntegerField(default=0, verbose_name='撈起次數'),
        ),
    ]
