# Generated by Django 4.2.30 on 2026-08-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_movie_original_title_movie_tmdb_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_user_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Google User ID'),
        ),
    ]
