# Generated by Django 4.2.30 on 2026-08-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_review_event_notification_invitetoken_directmessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='checked_in_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='registration_type',
            field=models.CharField(default='ONLINE', max_length=16),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='status',
            field=models.CharField(choices=[('REGISTERED', 'REGISTERED'), ('CHECKED_IN', 'CHECKED_IN'), ('NO_SHOW', 'NO_SHOW'), ('CANCELLED', 'CANCELLED')], default='REGISTERED', max_length=20),
        ),
    ]
