# Generated by Django 4.2.30 on 2026-08-28 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_review_event_notification_invitetoken_directmessage_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user', 'movie')},
        ),
    ]
