# Generated by Django 4.2.30 on 2026-08-28 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_eventregistration_checked_in_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='daily_digest_enabled',
            field=models.BooleanField(default=True, verbose_name='是否接收每日影迷日報'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, verbose_name='信箱是否已驗證'),
        ),
        migrations.CreateModel(
            name='DailyDigestLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('digest_date', models.DateField(auto_now_add=True)),
                ('unread_messages_count', models.IntegerField(default=0)),
                ('new_events_count', models.IntegerField(default=0)),
                ('delivery_channel', models.CharField(choices=[('EMAIL', 'Email'), ('LINE', 'LINE'), ('IN_APP_ONLY', 'In App Only'), ('SKIPPED', 'Skipped')], max_length=16)),
                ('delivery_status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('RATE_LIMITED', 'Rate Limited')], max_length=16)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_digest_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'digest_date'], name='api_dailydi_user_id_6e6dda_idx')],
                'unique_together': {('user', 'digest_date')},
            },
        ),
    ]
