# Generated by Django 4.2.30 on 2026-08-28 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_review_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
    ]
