# Generated by Django 4.2.30 on 2026-08-30 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_user_daily_digest_enabled_user_email_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='recap_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='回顧網址'),
        ),
    ]
