# Generated by Django 4.2.30 on 2026-09-02 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_event_recap_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='hours_tag',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='時數標籤'),
        ),
        migrations.AddField(
            model_name='event',
            name='requires_check_out',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='checked_out_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
