# Generated by Django 4.2.30 on 2026-09-07 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_event_hours_tag_event_requires_check_out_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='nickname_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='上次修改暱稱時間'),
        ),
    ]
