# Generated by Django 4.2.30 on 2026-09-12 06:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_userprofile_nickname_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='display_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='顯示日期（用戶自訂）'),
        ),
        migrations.AddField(
            model_name='tag',
            name='is_system',
            field=models.BooleanField(default=False, verbose_name='系統自動標籤'),
        ),
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='評分（1-5，可為空）'),
        ),
    ]
