# Generated by Django 4.2.30 on 2026-09-12 15:28
from django.db import migrations

def remove_self_follows(apps, schema_editor):
    Follow = apps.get_model('api', 'Follow')
    Notification = apps.get_model('api', 'Notification')
    User = apps.get_model('api', 'User')
    from django.db.models import F

    # 1. 刪除自己追蹤自己的資料
    Follow.objects.filter(follower=F('following')).delete()

    # 2. 刪除因為自己追蹤自己而產生的錯誤通知
    UserProfile = apps.get_model('api', 'UserProfile')
    for user in User.objects.all():
        try:
            profile = UserProfile.objects.get(user=user)
            nickname = profile.nickname or user.campus_id
        except UserProfile.DoesNotExist:
            nickname = user.campus_id
            
        # 找出 title 是 "XXX 發布了新心得..." 且 user 是自己的通知
        prefix = f"{nickname} 發布了新心得"
        Notification.objects.filter(user=user, type='new_review', title__startswith=prefix).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_review_display_date_tag_is_system_and_more'),
    ]

    operations = [
        migrations.RunPython(remove_self_follows, migrations.RunPython.noop),
    ]
