# Generated by Django 4.2.30 on 2026-09-13 06:07

from django.db import migrations


def cleanup_duplicates(apps, schema_editor):
    Review = apps.get_model('api', 'Review')
    from django.db.models import Count
    
    # 找到所有有發過多篇心得的 (user, movie) 組合
    duplicates = (
        Review.objects.filter(is_deleted=False)
        .values('user', 'movie')
        .annotate(count=Count('id'))
        .filter(count__gt=1)
    )
    
    for dup in duplicates:
        user_id = dup['user']
        movie_id = dup['movie']
        
        user_reviews = Review.objects.filter(user_id=user_id, movie_id=movie_id, is_deleted=False).order_by('-created_at')
        
        rapid_reviews = []
        normal_reviews = []
        
        for review in user_reviews:
            # 判斷是否為急速評星 (有急速評星標籤)
            if review.tags.filter(name="急速評星").exists():
                rapid_reviews.append(review)
            else:
                normal_reviews.append(review)
                
        # 保留最新的一般心得，刪除舊的
        if len(normal_reviews) > 1:
            # 第一個是最新的 (因為我們用了 -created_at)
            for review_to_delete in normal_reviews[1:]:
                # 完全刪除或是標記為 is_deleted=True
                review_to_delete.delete()
                
        # 保留最新的急速評星，刪除舊的 (防呆)
        if len(rapid_reviews) > 1:
            for review_to_delete in rapid_reviews[1:]:
                review_to_delete.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_remove_self_follows'),
    ]

    operations = [
        migrations.RunPython(cleanup_duplicates, migrations.RunPython.noop),
    ]
