# Generated by Django 4.2.30 on 2026-09-13 06:21

from django.db import migrations


def sync_daily_digest(apps, schema_editor):
    User = apps.get_model('api', 'User')
    
    # 有 Email 的使用者開啟系統信
    User.objects.exclude(email__isnull=True).exclude(email='').update(daily_digest_enabled=True)
    
    # 沒有 Email 的使用者關閉系統信
    User.objects.filter(email__isnull=True).update(daily_digest_enabled=False)
    User.objects.filter(email='').update(daily_digest_enabled=False)

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_cleanup_duplicate_reviews'),
    ]

    operations = [
        migrations.RunPython(sync_daily_digest, migrations.RunPython.noop),
    ]
