# Generated by Django 4.2.30 on 2026-10-08 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_promote_jlsrqytgp_to_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=60, verbose_name='片單標題')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='情境引言')),
                ('hashtags', models.JSONField(blank=True, default=list, verbose_name='主題標籤')),
                ('is_public', models.BooleanField(default=True, verbose_name='是否公開')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否已刪除')),
                ('bookmark_count', models.IntegerField(default=0, verbose_name='收藏次數')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curated_lists', to=settings.AUTH_USER_MODEL, verbose_name='策展人')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MovieListItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('curator_note', models.CharField(blank=True, default='', max_length=100, verbose_name='策展人短註')),
                ('order_index', models.IntegerField(default=0, verbose_name='排列順序')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_appearances', to='api.movie', verbose_name='電影')),
                ('movie_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.movielist', verbose_name='所屬片單')),
            ],
            options={
                'ordering': ['order_index'],
                'unique_together': {('movie_list', 'movie')},
            },
        ),
        migrations.CreateModel(
            name='MovieListBookmark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='api.movielist', verbose_name='片單')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_bookmarks', to=settings.AUTH_USER_MODEL, verbose_name='收藏者')),
            ],
            options={
                'unique_together': {('user', 'movie_list')},
            },
        ),
        migrations.AddIndex(
            model_name='movielist',
            index=models.Index(fields=['creator'], name='api_movieli_creator_6850b0_idx'),
        ),
        migrations.AddIndex(
            model_name='movielist',
            index=models.Index(fields=['-bookmark_count', '-created_at'], name='api_movieli_bookmar_cf8f42_idx'),
        ),
    ]
